# Scenario SCA: autenticazione a 2 fattori (2FA)
name: "2FA (SCA)"
interarrival_mean_s: 3.0
warmup_s: 1000.0
run_s: 10000.0
replications: 5
heavy_load: false
capacities:
  A: 1
  B: 1
  P: 1
service_demands:
  A:
    Class1: 0.2
    Class2: 0.4
    Class3: 0.15      # ↑ vs 1FA
  B:
    Class1: 0.8
    Class2: 0.0
    Class3: 0.0
  P:
    Class1: 0.0
    Class2: 0.7       # ↑ vs 1FA
    Class3: 0.0
