# 1FA con carico +15% sugli arrivi
name: "1FA (base) — heavy +15%"
interarrival_mean_s: 3.0
heavy_load: true              # ← abilita +15% sul tasso di arrivo
capacities:
  A: 1
  B: 1
  P: 1
service_demands:
  A:
    Class1: 0.2
    Class2: 0.4
    Class3: 0.1
  B:
    Class1: 0.8
    Class2: 0.0
    Class3: 0.0
  P:
    Class1: 0.0
    Class2: 0.4
    Class3: 0.0
